const express = require('express');
const home = require('./getAllPosts');
const displayPosts = require('./middleware/displayPosts');
const signup = require('./getSignup');
const checkIncomeData = require('./middleware/checkIncomeData');
const checkEmail = require('./middleware/checkEmailExist');
const hashingPassword = require('./middleware/hashingPassword');
const insertNewUser = require('./middleware/insertNewUser');
const postNewUser = require('./postNewUser');
const loginPage = require('./getLoginPage');
const comparePassword = require('./middleware/compareHashPassword');
const createCookie = require('./middleware/createCookie');
const postLogin = require('./postLogin');
const authentication = require('./middleware/authentication');
const checkToken = require('./middleware/checkToken');
const insertNewPost = require('./middleware/insertNewPost');
const postPost = require('./postPost');
const logout = require('./logout');
const deletePostDb = require('./middleware/deletePost');
const deletePost = require('./delete');
const updatePost = require('./middleware/updatePost');
const putPost = require('./putPost');
const error = require('./error');

const router = express.Router();
router.use(authentication.check);
router.get('/', displayPosts.display, home.get);
router.get('/signup', checkToken.checkUnsave, signup.get);
router.post('/checkSignup', checkToken.checkUnsave, checkIncomeData.checkInsert, checkEmail.check, hashingPassword.hash, insertNewUser.add, postNewUser.post);
router.get('/login', checkToken.checkUnsave, loginPage.get);
router.post('/checkLogin', checkToken.checkUnsave, checkIncomeData.checkLogin, checkEmail.checkLogin, comparePassword.compare, createCookie.cookie, postLogin.post);
router.get('/logout', checkToken.checkSave, logout.get);
router.post('/addPost', checkToken.checkSave, checkIncomeData.checkPost, insertNewPost.post, postPost.post);
router.delete('/deletePost', checkToken.checkSave, checkIncomeData.checkDelete, deletePostDb.deletePost, deletePost.delete);
router.put('/updatePost', checkToken.checkSave, checkIncomeData.checkUpdate, updatePost.updatePost, putPost.put);
router.use(error.client);
router.use(error.server);
module.exports = router;
